const DEFAULT_CONTAINER_WIDTH = 1200;
const DEFAULT_CONTAINER_HEIGHT = 800;

const DEFAULT_MAX_HEIGHT = Number.MAX_SAFE_INTEGER;
const DEFAULT_MAX_WIDTH = Number.MAX_SAFE_INTEGER;

const DEFAULT_MIN_HEIGHT = 400;
const DEFAULT_MIN_WIDTH = 600;

const DEFAULT_HEIGHT = DEFAULT_CONTAINER_WIDTH;
const DEFAULT_WIDTH = DEFAULT_CONTAINER_HEIGHT;

const DEFAULT_CELL_HEIGHT = 24;
const DEFAULT_MIN_CELL_WIDTH = 100;
const DEFAULT_CELL_PADDING = 8;
const DEFAULT_ROW_HEADER_WIDTH = 60;

const DEFAULT_BORDER_WIDTH = 1;
const DEFAULT_FONT_FAMILY = "Consolas, monospace";
const DEFAULT_FONT_SIZE = 14;
const DEFAULT_HEADER_FONT_SIZE = 14;
const DEFAULT_HEADER_BACKGROUND_COLOR = "#f0f0f0";
const DEFAULT_HEADER_TEXT_COLOR = "#333";
const DEFAULT_CELL_BACKGROUND_COLOR = "#fff";
const DEFAULT_CELL_TEXT_COLOR = "#000";
const DEFAULT_BORDER_COLOR = "#ddd";
const DEFAULT_SELECTION_COLOR = "rgba(0, 120, 215, 0.2)";
const DEFAULT_HOVER_COLOR = "rgba(0, 120, 215, 0.1)";

const DEFAULT_SCROLLBAR_WIDTH = 12;
const DEFAULT_SCROLLBAR_COLOR = "#e0e0e0";
const DEFAULT_SCROLLBAR_THUMB_COLOR = "#b0b0b0";
const DEFAULT_SCROLLBAR_HOVER_COLOR = "#909090";

const DEFAULT_DATE_FORMAT = "yyyy-MM-dd";
const DEFAULT_DATETIME_FORMAT = "yyyy-MM-dd HH:mm:ss";
const DEFAULT_NUMBER_FORMAT = { minimumFractionDigits: 2, maximumFractionDigits: 2 };

export {
  DEFAULT_CONTAINER_WIDTH,
  DEFAULT_CONTAINER_HEIGHT,
  DEFAULT_MAX_HEIGHT,
  DEFAULT_MAX_WIDTH,
  DEFAULT_MIN_HEIGHT,
  DEFAULT_MIN_WIDTH,
  DEFAULT_HEIGHT,
  DEFAULT_WIDTH,
  DEFAULT_CELL_HEIGHT,
  DEFAULT_MIN_CELL_WIDTH,
  DEFAULT_CELL_PADDING,
  DEFAULT_ROW_HEADER_WIDTH,
  DEFAULT_BORDER_WIDTH,
  DEFAULT_FONT_FAMILY,
  DEFAULT_FONT_SIZE,
  DEFAULT_HEADER_FONT_SIZE,
  DEFAULT_HEADER_BACKGROUND_COLOR,
  DEFAULT_HEADER_TEXT_COLOR,
  DEFAULT_CELL_BACKGROUND_COLOR,
  DEFAULT_CELL_TEXT_COLOR,
  DEFAULT_BORDER_COLOR,
  DEFAULT_SELECTION_COLOR,
  DEFAULT_HOVER_COLOR,
  DEFAULT_SCROLLBAR_WIDTH,
  DEFAULT_SCROLLBAR_COLOR,
  DEFAULT_SCROLLBAR_THUMB_COLOR,
  DEFAULT_SCROLLBAR_HOVER_COLOR,
  DEFAULT_DATE_FORMAT,
  DEFAULT_DATETIME_FORMAT,
  DEFAULT_NUMBER_FORMAT,
};
